<a href="https://colab.research.google.com/github/HochenM/-ErbB-Oligomer-PCA/blob/main/Session_10_ml_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install cuml-cu11 --extra-index-url=https://pypi.nvidia.com


Looking in indexes: https://pypi.org/simple, https://pypi.nvidia.com
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.2/8.2 MB 30.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 136.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 832.7/832.7 kB 226.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 138.4/138.4 kB 133.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.8/50.8 kB 67.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 139.9/139.9 MB 16.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 168.4/168.4 MB 66.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.1/58.1 MB 62.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 128.2/128.2 MB 91.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 204.1/204.1 MB 33.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 855.0/855.0 kB 87.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

In [20]:
import cuml
cuml.__version__


'25.06.00'

In [ ]:
!pip install cudf-cu11 cuml-cu11 --extra-index-url=https://pypi.nvidia.com


Looking in indexes: https://pypi.org/simple, https://pypi.nvidia.com


In [21]:
import cudf

cudf.__version__

'25.06.00'

In [ ]:
dir(cuml)

['ARIMA',
 'AgglomerativeClustering',
 'AutoARIMA',
 'Base',
 'CD',
 'DBSCAN',
 'ElasticNet',
 'ExponentialSmoothing',
 'ForestInference',
 'GaussianRandomProjection',
 'GlobalSettings',
 'HDBSCAN',
 'Handle',
 'IncrementalPCA',
 'KMeans',
 'KNeighborsClassifier',
 'KNeighborsRegressor',
 'KernelDensity',
 'KernelExplainer',
 'KernelRidge',
 'LabelEncoder',
 'Lasso',
 'LinearRegression',
 'LinearSVC',
 'LinearSVR',
 'LogisticRegression',
 'MBSGDClassifier',
 'MBSGDRegressor',
 'MultinomialNB',
 'NearestNeighbors',
 'PCA',
 'PermutationExplainer',
 'QN',
 'RandomForestClassifier',
 'RandomForestRegressor',
 'Ridge',
 'SGD',
 'SVC',
 'SVR',
 'SparseRandomProjection',
 'TSNE',
 'TreeExplainer',
 'TruncatedSVD',
 'UMAP',
 'UniversalBase',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__getattr__',
 '__git_commit__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_global_settings_data',
 '_thirdparty',
 '_version',
 'accel',


In [2]:
from sklearn.datasets import load_digits, fetch_openml
from sklearn.model_selection import train_test_split, learning_curve
from cuml.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
X, y = fetch_openml("mnist_784", as_frame=False, return_X_y=True)


X.shape

(70000, 784)

In [4]:
from tensorflow.keras.datasets import mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()

x_train = x_train.reshape(60000,784)
x_test = x_test.reshape(10000,784)

x_train.shape

11490434/11490434 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step


(60000, 784)

In [5]:
model = LogisticRegression(max_iter=
1000)

In [6]:
result = learning_curve(
    model,
    x_train, y_train,
    train_sizes=[0.4,0.5,0.6,0.7,0.8,0.9],
    scoring="accuracy",
    verbose=10
)

[learning_curve] Training set sizes: [19200 24000 28800 33600 38400 43200]
[CV] START .....................................................................
[2026-06-04 11:59:14.531] [CUML] [warning] L-BFGS: max iterations reached
[2026-06-04 11:59:14.532] [CUML] [warning] Maximum iterations reached before solver is converged. To increase model accuracy you can increase the number of iterations (max_iter) or improve the scaling of the input data.
[CV] END ..................., score=(train=0.979, test=0.872) total time=   4.5s
[CV] START .....................................................................


[Parallel(n_jobs=1)]: Done   1 tasks      | elapsed:    4.6s


[2026-06-04 11:59:16.430] [CUML] [warning] L-BFGS: max iterations reached
[2026-06-04 11:59:16.430] [CUML] [warning] Maximum iterations reached before solver is converged. To increase model accuracy you can increase the number of iterations (max_iter) or improve the scaling of the input data.
[CV] END ..................., score=(train=0.966, test=0.889) total time=   1.5s
[CV] START .....................................................................
[2026-06-04 11:59:18.208] [CUML] [warning] L-BFGS: max iterations reached
[2026-06-04 11:59:18.208] [CUML] [warning] Maximum iterations reached before solver is converged. To increase model accuracy you can increase the number of iterations (max_iter) or improve the scaling of the input data.
[CV] END ..................., score=(train=0.955, test=0.897) total time=   1.7s
[CV] START .....................................................................
[2026-06-04 11:59:20.327] [CUML] [warning] L-BFGS: max iterations reached
[2026-06-04 11

[Parallel(n_jobs=1)]: Done   4 tasks      | elapsed:   10.0s


[2026-06-04 11:59:22.536] [CUML] [warning] L-BFGS: max iterations reached
[2026-06-04 11:59:22.536] [CUML] [warning] Maximum iterations reached before solver is converged. To increase model accuracy you can increase the number of iterations (max_iter) or improve the scaling of the input data.
[CV] END ..................., score=(train=0.946, test=0.909) total time=   2.2s
[CV] START .....................................................................
[2026-06-04 11:59:25.097] [CUML] [warning] L-BFGS: max iterations reached
[2026-06-04 11:59:25.098] [CUML] [warning] Maximum iterations reached before solver is converged. To increase model accuracy you can increase the number of iterations (max_iter) or improve the scaling of the input data.
[CV] END ..................., score=(train=0.943, test=0.911) total time=   2.5s
[CV] START .....................................................................
[2026-06-04 11:59:26.418] [CUML] [warning] L-BFGS: max iterations reached
[2026-06-04 11

[Parallel(n_jobs=1)]: Done   7 tasks      | elapsed:   16.1s


[2026-06-04 11:59:27.911] [CUML] [warning] L-BFGS: max iterations reached
[2026-06-04 11:59:27.911] [CUML] [warning] Maximum iterations reached before solver is converged. To increase model accuracy you can increase the number of iterations (max_iter) or improve the scaling of the input data.
[CV] END ..................., score=(train=0.970, test=0.876) total time=   1.5s
[CV] START .....................................................................
[2026-06-04 11:59:29.640] [CUML] [warning] L-BFGS: max iterations reached
[2026-06-04 11:59:29.640] [CUML] [warning] Maximum iterations reached before solver is converged. To increase model accuracy you can increase the number of iterations (max_iter) or improve the scaling of the input data.
[CV] END ..................., score=(train=0.959, test=0.885) total time=   1.7s
[CV] START .....................................................................
[2026-06-04 11:59:31.681] [CUML] [warning] L-BFGS: max iterations reached
[2026-06-04 11

[Parallel(n_jobs=1)]: Done  12 tasks      | elapsed:   26.1s


[2026-06-04 11:59:37.759] [CUML] [warning] L-BFGS: max iterations reached
[2026-06-04 11:59:37.760] [CUML] [warning] Maximum iterations reached before solver is converged. To increase model accuracy you can increase the number of iterations (max_iter) or improve the scaling of the input data.
[CV] END ..................., score=(train=0.983, test=0.864) total time=   1.2s
[CV] START .....................................................................
[2026-06-04 11:59:39.271] [CUML] [warning] L-BFGS: max iterations reached
[2026-06-04 11:59:39.271] [CUML] [warning] Maximum iterations reached before solver is converged. To increase model accuracy you can increase the number of iterations (max_iter) or improve the scaling of the input data.
[CV] END ..................., score=(train=0.968, test=0.880) total time=   1.5s
[CV] START .....................................................................
[2026-06-04 11:59:41.016] [CUML] [warning] L-BFGS: max iterations reached
[2026-06-04 11

[Parallel(n_jobs=1)]: Done  17 tasks      | elapsed:   35.1s


[2026-06-04 11:59:47.870] [CUML] [warning] L-BFGS: max iterations reached
[2026-06-04 11:59:47.870] [CUML] [warning] Maximum iterations reached before solver is converged. To increase model accuracy you can increase the number of iterations (max_iter) or improve the scaling of the input data.
[CV] END ..................., score=(train=0.945, test=0.907) total time=   2.4s
[CV] START .....................................................................
[2026-06-04 11:59:49.209] [CUML] [warning] L-BFGS: max iterations reached
[2026-06-04 11:59:49.210] [CUML] [warning] Maximum iterations reached before solver is converged. To increase model accuracy you can increase the number of iterations (max_iter) or improve the scaling of the input data.
[CV] END ..................., score=(train=0.985, test=0.860) total time=   1.3s
[CV] START .....................................................................
[2026-06-04 11:59:50.741] [CUML] [warning] L-BFGS: max iterations reached
[2026-06-04 11

[Parallel(n_jobs=1)]: Done  24 tasks      | elapsed:   49.1s


[2026-06-04 12:00:00.779] [CUML] [warning] L-BFGS: max iterations reached
[2026-06-04 12:00:00.779] [CUML] [warning] Maximum iterations reached before solver is converged. To increase model accuracy you can increase the number of iterations (max_iter) or improve the scaling of the input data.
[CV] END ..................., score=(train=0.983, test=0.882) total time=   1.3s
[CV] START .....................................................................
[2026-06-04 12:00:02.325] [CUML] [warning] L-BFGS: max iterations reached
[2026-06-04 12:00:02.325] [CUML] [warning] Maximum iterations reached before solver is converged. To increase model accuracy you can increase the number of iterations (max_iter) or improve the scaling of the input data.
[CV] END ..................., score=(train=0.967, test=0.898) total time=   1.5s
[CV] START .....................................................................
[2026-06-04 12:00:04.121] [CUML] [warning] L-BFGS: max iterations reached
[2026-06-04 12

[Parallel(n_jobs=1)]: Done  30 out of  30 | elapsed:  1.0min finished


In [7]:
result

(array([19200, 24000, 28800, 33600, 38400, 43200]),
 array([[0.97864583, 0.9853125 , 0.983125  , 0.98520833, 0.983125  ],
        [0.96554167, 0.97004167, 0.967875  , 0.96758333, 0.9665    ],
        [0.95510417, 0.95878472, 0.95722222, 0.95822917, 0.95795139],
        [0.94872024, 0.95125   , 0.9521131 , 0.9527381 , 0.95300595],
        [0.94559896, 0.94757813, 0.94710938, 0.95007812, 0.94859375],
        [0.94347222, 0.9449537 , 0.94474537, 0.94696759, 0.9450463 ]]),
 array([[0.8715    , 0.86025   , 0.864     , 0.86008333, 0.88225   ],
        [0.88875   , 0.87575   , 0.87975   , 0.87533333, 0.89833333],
        [0.89691667, 0.8855    , 0.88858333, 0.886     , 0.9055    ],
        [0.90283333, 0.89608333, 0.895     , 0.8915    , 0.90941667],
        [0.90925   , 0.9005    , 0.90333333, 0.89725   , 0.91516667],
        [0.91058333, 0.90508333, 0.90733333, 0.90216667, 0.91691667]]))